restart_file: .na
start_datetime: 2023-10-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2024-02-02 00:00:00
forecast_horizon: 34.0
sim_name: test_runS3
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: true

