restart_file: .na
start_datetime: 2022-05-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-07-30 00:00:00
forecast_horizon: 35
sim_name: long_da_4zones
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: FALSE
