restart_file: .na
start_datetime: 2022-05-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-06-30 00:00:00
forecast_horizon: 35
sim_name: short_da_3zones_ksed7.4_neg0.01fsed_200ens_decreaseinito2
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: FALSE
