restart_file: .na
start_datetime: 2021-06-01 16:00:00 # spinup start time
end_datetime: .na # spinup end time, if not specified, then defaults to when forecasts start
forecast_start_datetime: 2021-06-05 16:00:00 # noon EST
forecast_horizon: 35
sim_name: short_DA_noaa_met
forecast_output_directory: .na
forecast_configuration_directory: .na
execute_directory: .na
