restart_file: .na
start_datetime: 2010-07-02 00:00:00 # spinup start time
end_datetime: .na # spinup end time, if not specified, then defaults to when forecasts start
forecast_start_datetime: 2010-07-05 00:00:00
forecast_horizon: 3.0
sim_name: test_run
forecast_output_directory: .na
forecast_configuration_directory: .na
execute_directory: .na
