restart_file: .na
start_datetime: 2021-10-15 00:00:00
end_datetime: .na
forecast_start_datetime: 2021-10-17 00:00:00
forecast_horizon: 35
sim_name: short_DA_noaa_met
forecast_output_directory: .na
forecast_configuration_directory: .na
execute_directory: .na
forecast_site: sunp
