#FULL PATHS
qaqc_data_location: paste0(getwd(), '/working_directory') # does this just need a temporary directory?
data_location: paste0(getwd(), '/data_processing/input_data') # is this where FLARE will access driver data?

##########################
# Lake information
###########################

lake_name_code: sunp
lake_name: Lake Sunapee
lake_latitude: 43.3913   #Degrees North, taken from EDI 
lake_longitude: 72.0576  #Degrees West, taken from EDI

#Time zone that GLM is run in
#Currently needed to be GMT so that it interfaces with the NOAA forecast
#reference_tzone <<- "GMT"
#Local time zone of the lake
local_tzone: "EST" # UTC-5??

##########################
#  Information required to generate EML metadata file
##########################

metadata:
    forecast_project_id: test
    generate_eml: TRUE
    abstract: "This is where a longer description of the forest can be added"
    forecast_title: FLARE
    intellectualRights: insert license
    model_description:
        forecast_model_id: https://github.com/rqthomas/flare/commit/d1ddcb07b9d28863890597503fc4aa4a4496de56
        name: General Lake Model
        type: process-based
        repository: https://github.com/AquaticEcoDynamics/GLM/releases/tag/v3.1.0
    me:
        individualName:
              givenName: "Whitney"
              surName: "Woelmer"
        electronicMailAddress:  "wwoelmer@vt.edu"
        id: INSERT ORCID

############################
# Run information
#############################

model_name: glm_aed #other is "null"

# Relative to forecast_location

base_GLM_nml: glm3_woAED.nml

#All sources of uncertainty and data used to constrain
use_obs_constraint: TRUE
observation_uncertainty: TRUE
process_uncertainty: TRUE
weather_uncertainty: TRUE
initial_condition_uncertainty: TRUE
parameter_uncertainty: TRUE
met_downscale_uncertainty: TRUE
inflow_process_uncertainty: TRUE

use_forecasted_met: TRUE
forecast_met_model: NOAAGEFS_1hr-debias

#forecast_inflow_model: FLOWS-NOAAGEFS-AR1

use_future_inflow: FALSE
#future_inflow_flow_coeff: [0.0010803, 0.9478724, 0.3478991]
#future_inflow_flow_error: 0.00965
#future_inflow_temp_coeff: [0.20291, 0.94214, 0.04278]
#future_inflow_temp_error: 0.943

#########################
### Depth information
#########################
#Depths used in the EnKF
#This are the depths that are saved between days
#Init depth of lake
lake_depth_init: 33  #not a modeled state

depths_bins_top: [0.0, 0.1, 0.33, 0.67,
                1.00, 1.33, 1.67,
                2.00, 2.33, 2.67,
                3.00, 3.33, 3.67,
                4.00, 4.33, 4.67,
                5.00, 5.33, 5.67,
                6.00, 6.33, 6.67,
                7.00, 7.33, 7.67,
                8.00, 8.33, 8.67,
                9.00, 9.33, 10,
                15, 20, 25, 30, 33]

# shouldn't they change based on when you are starting the model?
default_temp_init: [25.667, 24.9101, 23.067, 21.8815, 19.6658, 16.5739, 12.9292, 12.8456, 12.8127, 12.8079, 12.778]
default_temp_init_depths: [0.127, 1.004, 2.005, 3.021, 4.002, 5.004, 6.004, 7.01, 8.001, 9.015, 9.518]
the_sals_init: 0.0

default_snow_thickness_init: 0.0
default_white_ice_thickness_init: 0.0
default_blue_ice_thickness_init: 0.0


##############################
##  EnKF setup
##############################
da_method: "enkf"
par_fit_method: "inflate"
ensemble_size:  100
localization_distance: .na #distance in meters were covariances in the model error are used
vert_decorr_length: 5.0
no_negative_states: TRUE
assimilate_first_step: FALSE
ncore: 2

#################################
# Parameter calibration information
#################################

par_file: parameter_calibration_config.csv # this is the file where you specify what params to fit

#####################################
###  Observation information
######################################

obs_config_file: observations_config.csv # file where you specify which type of observations you have data for and the uncertainty around that data

#########################################
###  State information
#########################################

states_config_file: states_config.csv
states_config_process_error: states_process_error.csv

#carbon to chlorophyll ratio (mg C/mg chla)
#12 g/ mole of C vs. X g/ mole of chla
#Initial concentration of phytoplankton (mmol C/m3)
# biomass_to_chla <<- c((160/12),(60/12), (60/12))

########################################
# Diagnostics
#######################################

diagnostics_names:  [extc_coef]


