on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"

jobs:
# Point to the right path, run the right Rscript command
    run_default:
       name: Run default automatic prediction file
          runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.2.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: /usr/local/bin/r $GITHUB_WORKSPACE/workflows/default/combined_workflow.R
        
    run_default_temp_oxy:
      name: Run default automatic prediction file
          runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.2.1
    steps:
      name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: /usr/local/bin/r $GITHUB_WORKSPACE/workflows/default_temp_oxy/combined_workflow.R
